### PR TITLE
Makes additional_inputs accept targets

### LINKED ISSUE #451: How one can use the additional_inputs attribute?
Taking examples/simple_make as example:

```diff
 make(
     name = "make_lib",
     lib_source = "//simple_make/code:sources",
+    additional_inputs = [
+        "test_libb.cpp",
+    ],
     static_libraries = ["liba.a"],
 )
```

Then trying to build:

```bash
bazel build simple_make:make_lib
```

Result: Error, cannot add a 'Target' to a depset of 'File'

```
ERROR: /home/rafael/my_github/rules_foreign_cc/examples/simple_make/BUILD:3:5: in make rule //simple_make:make_lib: 
Traceback (most recent call last):
        File "/home/rafael/b/external/rules_foreign_cc/tools/build_defs/make.bzl", line 32, column 33, in _make
                return cc_external_rule_impl(ctx, attrs)
        File "/home/rafael/b/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 281, column 24, in cc_external_rule_impl
                inputs = depset(inputs.declared_inputs, transitive = [ctx.attr._cc_toolchain.files]),
Error in depset: cannot add an item of type 'Target' to a depset of 'File'
ERROR: Analysis of target '//simple_make:make_lib' failed; build aborted: Analysis of target '//simple_make:make_lib' failed
```

I've created a PR  #450 to treat this. Any other suggestions?

### PR DESCRIPTION
**Pull request by rqssouza**
Makes additional_inputs attribute also accept bazel Targets as inputs, just like lib_source attribute already does. 
Fixes #451

### CODE REVIEW

**Comment by whs-dot-hk** [comment]
@rqssouza I also agree this is a bug,

Referencing
https://github.com/bazelbuild/rules_foreign_cc/blob/d54c78ab86b40770ee19f0949db9d74a831ab9f0/tools/build_defs/framework.bzl#L586
which `tools_deps` is also of type `label_list`

You could sure patch it like
```patch
diff --git a/tools/build_defs/framework.bzl b/tools/build_defs/framework.bzl
index 7277161..90bb269 100644
--- a/tools/build_defs/framework.bzl
+++ b/tools/build_defs/framework.bzl
@@ -580,6 +580,7 @@ def _define_inputs(attrs):
 
     tools_roots = []
     tools_files = []
+    inputs_files = []
     for tool in attrs.tools_deps:
         tool_root = detect_root(tool)
         tools_roots.append(tool_root)
@@ -587,9 +588,13 @@ def _define_inputs(attrs):
             tools_files += _list(file_list)
 
     for tool in attrs.additional_tools:
-        for file_list in tool.files:
+        for file_list in tool.files.to_list():
             tools_files += _list(file_list)
 
+    for i in attrs.additional_inputs:
+        for l in i.files.to_list():
+            inputs_files += _list(l)
+
     # These variables are needed for correct C/C++ providers constraction,
     # they should contain all libraries and include directories.
     cc_info_merged = cc_common.merge_cc_infos(cc_infos = cc_infos)
@@ -605,7 +610,7 @@ def _define_inputs(attrs):
         declared_inputs = filter_containing_dirs_from_inputs(attrs.lib_source.files.to_list()) +
                           bazel_libs +
                           tools_files +
-                          attrs.additional_inputs +
+                          inputs_files +
                           cc_info_merged.compilation_context.headers.to_list() +
                           ext_build_dirs,
     )
```
Change the `i` and `l` above.

Notice I also updated `additional_tools`.

**Comment by rqssouza** [comment]
@whs-dot-hk Sure, much better. I hadn't seen the additional_tools had the same bug. So in the end everything will accept just 'Target's

**Comment by whs-dot-hk** [comment]
Yes, because `label_list` https://docs.bazel.build/versions/master/skylark/lib/attr.html#label_list
accepts only targets

**Comment by rqssouza** [comment]
recheck

**Review by jsharpe — APPROVED** [review]
Thanks @rqssouza LGTM

**Pull request merged**
