### PR TITLE
Built ninja tools no longer carry the entire source tree

### PR DESCRIPTION
**Pull request by UebelAndre**
This should be a nice optimization to what was there before but function the same

### CODE REVIEW

**Review by jsharpe — APPROVED** [review]

**Review by jsharpe — CHANGES_REQUESTED** [review]
Looks like this breaks building make on RBE unfortunately :(

**Review by jsharpe — APPROVED** [review]
Only observation I have is that by putting the ninja binary into a bin directory this will possibly remove the binary from the path in the same way that make is missing - see #590. This would  impact configure scripts that are expecting to find ninja on the path, assuming that it hits the same bug, but we should probably fix that anyway.

**Comment by UebelAndre** [comment]
> Only observation I have is that by putting the ninja binary into a bin directory this will possibly remove the binary from the path in the same way that make is missing - see #590. This would impact configure scripts that are expecting to find ninja on the path, assuming that it hits the same bug, but we should probably fix that anyway.

so is the path not to use `./bin` or to ensure the PATH variable is appropriately updated? I'd prefer the latter. I dislike how there's a single directory that gets a bunch of stuff copied to it. I'd rather just add the correct paths to the binaries to PATH without moving any files.

**Comment by jsharpe** [comment]
> > Only observation I have is that by putting the ninja binary into a bin directory this will possibly remove the binary from the path in the same way that make is missing - see #590. This would impact configure scripts that are expecting to find ninja on the path, assuming that it hits the same bug, but we should probably fix that anyway.
> 
> so is the path not to use `./bin` or to ensure the PATH variable is appropriately updated? I'd prefer the latter. I dislike how there's a single directory that gets a bunch of stuff copied to it. I'd rather just add the correct paths to the binaries to PATH without moving any files.

AFAIK (but I might be wrong here!) the built ninja would get linked in as `$EXT_BUILD_DEPS/bin/ninja_tool/bin/ninja` and I think that the issue is that the find call to add that to the path is restricted to 1 directory deep. I agree that we should be updating the PATH variable appropriately for this case.

**Comment by UebelAndre** [comment]
> AFAIK (but I might be wrong here!) the built ninja would get linked in as `$EXT_BUILD_DEPS/bin/ninja_tool/bin/ninja` and I think that the issue is that the find call to add that to the path is restricted to 1 directory deep. I agree that we should be updating the PATH variable appropriately for this case.

Yeah, I don't understand why we're doing `$EXT_BUILD_DEPS/bin/ninja_tool/bin/ninja`. I think it's fine if we're gonna muck with the PATH variable but I don't think we should be need to make this `$EXT_BUILD_DEPS/bin` directory. Though I think this goes into a larger discussion about why we don't build from the standard exec root.

**Pull request merged**
