### PR TITLE
Add make 4.4.1

### PR DESCRIPTION
**Pull request by novas0x2a**
It was released a while ago, and, although I haven't been able to track down the exact reason why, I keep seeing jobserver failures (on linux) that don't happen on either 4.3 or 4.4.1, leading me to believe there's probably a bug in the new 4.4 jobserver code that was fixed in 4.4.1.

### CODE REVIEW

**Review by jsharpe — APPROVED** [review]
Thanks!

**Comment by novas0x2a** [comment]
One thing to note is this will emit a warning until make-4.4.1 is uploaded to the bazel mirror; are you able to do that?

**Comment by jsharpe** [comment]
> One thing to note is this will emit a warning until make-4.4.1 is uploaded to the bazel mirror; are you able to do that?

There's an issue template in bazelbuild/bazel to request a new package be added to the mirror. Anyone can fill that out.

**Comment by novas0x2a** [comment]
Ah, didn't realize that. Filed: https://github.com/bazelbuild/bazel/issues/21039

**Pull request merged**
