### PR TITLE
Add a new cmake option 'cmake_relative_root'.

### PR DESCRIPTION
**Pull request by stellaraccident**
This makes it possible to build LLVM (by passing "llvm" for this new
option).

### CODE REVIEW

**Comment by lopter** [comment]
Hi, thanks for the patch! I have also used that to build libdbus 1.12.16 which doesn't have its `CMakeLists.txt` at the root.

**Comment by attilaolah** [comment]
Same thing for `ztd`, it has its `CMakeLists.txt` under `build/cmake`.

I was thinking that it would also be possible to find the most root-level `CMakeLists.txt`, similarly to how `find_root` works. That would make most of these packages work without needing to specify cmake_relative_root.

**Comment by irengrig** [comment]
Hi @stellaraccident , thank you for the pull request!
Is that possible to see the example of the usage?

And also, we should change the comment about the "root" parameter in create_cmake_script in cmake_script.bzl to "working directory for invoking cmake and build tool (make/Ninja/MSBuild)"

**Comment by irengrig** [comment]
Implemented in #390: https://github.com/bazelbuild/rules_foreign_cc/blob/d838bc55067fc473fa67ec619be1478e45b96e2d/tools/build_defs/cmake.bzl#L119.

Sorry, I did not connect this PR to the problem at the moment when I did #390.

**Pull request closed without merging**
