### PR TITLE
Ensure Windows paths provided to CMake contain forward slashes only

### PR DESCRIPTION
**Pull request by jheaff1**
CMake will fail if the cross tool file generated by rules_foreign_cc  contains backslashes.

### CODE REVIEW

**Comment by jheaff1** [comment]
@jsharpe @UebelAndre May I please request a review of this PR 😁

**Comment by UebelAndre** [comment]
Can you maybe share the callstack of some issue this is solving? So I understand the issue?

**Comment by jheaff1** [comment]
@UebelAndre Apologies for the delay in getting back to you.

I am trying to build `zlib` using a hermetic Android toolchain. The `crosstool_bazel.cmake` file that rules_foreign_cc generates contains the following:


```
set(CMAKE_CXX_FLAGS_INIT "-isystem C:\msys64\home\jheaf\_bazel_jheaf\mnvfelgc\execroot\bazel-example/external/customandroidsdk/ndk/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/ -isystem C:\msys64\home\jheaf\_bazel_jheaf\mnvfelgc\execroot\bazel-example/external/customandroidsdk/ndk/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/ -isystem C:\msys64\home\jheaf\_bazel_jheaf\mnvfelgc\execroot\bazel-example/external/customandroidsdk/ndk/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/arm-linux-androideabi/ -target armv7a-linux-androideabi21 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -no-canonical-prefixes --sysroot=C:\msys64\home\jheaf\_bazel_jheaf\mnvfelgc\execroot\bazel-example/external/customandroidsdk/ndk/toolchains/llvm/prebuilt/windows-x86_64/sysroot -std=c++17")
set(CMAKE_C_COMPILER "C:\msys64\home\jheaf\_bazel_jheaf\mnvfelgc\execroot\bazel-example/external/customandroidsdk/ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe")
```

Notice how the paths start with backward slashes, i.e. `C:\msys64\home\........".

zlib fails to build because cmake reports a syntax error in `crosstool_bazel.cmake`:

```
  Syntax error in cmake code at

    C:/msys64/home/jheaf/_bazel_jheaf/mnvfelgc/execroot/bazel-example/bazel-out/x64_windows-fastbuild/bin/external/zlib/zlib.build_tmpdir/CMakeFiles/3.21.2/CMakeCCompiler.cmake:1

  when parsing string

    C:\msys64\home\jheaf\_bazel_jheaf\mnvfelgc\execroot\bazel-example/external/customandroidsdk/ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

  Invalid escape sequence \m
```

This PR changes rules_foreign_cc so that all backslashes in paths are replaced with forward slashes, which resolves the issue.

Hope that made sense

**Review by UebelAndre — APPROVED** [review]
Thanks! I think this looks fine to me but would like @jsharpe to also take a look

**Review by jsharpe — APPROVED** [review]
LGTM

**Pull request merged**
