### PR TITLE
Remove a print from the cleanup function

### PR DESCRIPTION
**Pull request by attilaolah**
It somehow causes empty newlines to be printed in Bazel build output.

Cherry-picked from c835382026896f4316b3a1af9164977eeb46abea.

### CODE REVIEW

**Comment by attilaolah** [comment]
Apparently this does fix the spurious newlines, but I have zero clue why. In any case, I extracted it out of #479 since it is unrelated to that change.

**Review by UebelAndre — APPROVED** [review]

**Comment by UebelAndre** [comment]
Just need CLA

**Comment by attilaolah** [comment]
@scele could you please ack the CLA if you're OK with merging this?

Thanks!

**Comment by UebelAndre** [comment]
Pinging this PR again. I'd be nice to get this in 😄

**Comment by UebelAndre** [comment]
A similar change was made in https://github.com/bazelbuild/rules_foreign_cc/pull/501 so this is not needed anymore. Thanks for the PR though!

**Pull request closed without merging**
