### PR TITLE
Fix string escaping for cmake and configure/make

### PR DESCRIPTION
**Pull request by wolfd**
Refresh of #362.
Related to discussion in #239.

To be honest, this isn't the cleanest stuff in the world, but it works in my limited testing. There's a number of layers to this which I think is the cause of past confusion here. There's a lot of instances of strings getting escaped at the wrong stage, and I think it's almost pure luck that this particular combination of escape sequences actually works.

Usage of this PR that I used to "test" it:
- [Using configure_make to build Python 3.8](https://github.com/wolfd/rules_foreign_cc/commit/79a127e23b21bf289f411b4524474a573157977a)
- [CMake usage similar to how Python uses `__TIME__`](https://github.com/wolfd/rules_foreign_cc/blob/72d01448ca0a9704e4298e67424fcae616068308/examples/cmake_defines/lib_a/lib_a.cpp)

It occurs to me that actually compiling stuff in examples might be a good thing to do as part of tests, is there a reason that currently isn't the case?

### CODE REVIEW

**Comment by wolfd** [comment]
Things are moving quite quick on `main`! Exciting! (I resolved some conflicts)

**Comment by UebelAndre** [comment]
Hey, thanks for the PR! I think we just got through some of the larger structural changes that would lead to conflicts. From here on I expect more targeted changes. 

Do you think there's a quick change you could also make to one of the examples that would exercise the fix here? The examples seem to do all the heavy lifting in terms of regression testing and would prefer to have something there. 🙏

**Comment by wolfd** [comment]
@googlebot I consent.

**Comment by jsharpe** [comment]
@googlebot I consent.

**Comment by jsharpe** [comment]
PTAL @UebelAndre

**Review by UebelAndre — CHANGES_REQUESTED** [review]
Very nice!!

**Review by UebelAndre — APPROVED** [review]

**Comment by UebelAndre** [comment]
(sorry about the misclick) very excited to see this go in, Thank you so much for the PR! 🙏

**Pull request merged**
