### PR TITLE
Fix replace_in_files function in windows_commands.bzl

### LINKED ISSUE #279: The replace_in_files step damages executables on Windows
Building a simple hello world application fails because the replace_in_files steps damage the generated executables.

When I try to run the executable (`bazel-out\x64_windows-fastbuild\bin\example\bin\CMakeHelloWorld.exe`) an error message pops up: "Unsupported 16-Bit Application".

Inspection shows that file sizes of executables in the tmp directory and bazel-out directory are different:
```
Directory of c:\Tools\msys64\tmp\tmp.sxrshV3C81\example\bin

25-06-2019  11:03            15.872 CMakeHelloWorld.exe
```
```
Directory of bazel-out\x64_windows-fastbuild\bin\example\bin

25-06-2019  11:03            15.861 CMakeHelloWorld.exe
```

WORKSPACE:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
   name = "rules_foreign_cc",
   strip_prefix = "rules_foreign_cc-master",
   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip",
   sha256 = "0b217f388a031941cde4b095afa9214958408ec0f0d607202959eceac5008f0d",
)
load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")
rules_foreign_cc_dependencies()

http_archive(
    name = "cmake-hello-world",
    build_file_content = """filegroup(name = "all", srcs = glob(["**"]), visibility = ["//visibility:public"])""",
    strip_prefix = "cmake-hello-world-master",
    urls = ["https://github.com/jameskbride/cmake-hello-world/archive/master.zip"],
    sha256 = "d613cf222bbb05b8cff7a1c03c37345ed33744a4ebaf3a8bfd5f56a76e25ca08",
)
```
BUILD:
```
load("@rules_foreign_cc//tools/build_defs:cmake.bzl", "cmake_external")

cmake_external(
    name = "example",
    lib_source = "@cmake-hello-world//:all",
    generate_crosstool_file = True,
    cmake_options = ["-GNinja"],
    make_commands = ["ninja", "ninja install"],
    binaries = ["CMakeHelloWorld.exe"],
)
```

I was able to work around this issue by setting `make_commands = ["function replace_in_files() { : ; }", "ninja", "ninja install"]` in the `cmake_external` rule.

### PR DESCRIPTION
**Pull request by irengrig**
Filter files by types, where the absolute paths need to be replaced.

Fixes #279

### CODE REVIEW

**Comment by irengrig** [comment]
The introduced test really fails without the fix: #281

**Comment by wrowe** [comment]
For further details of how bazel is attempting to build the c-ares project whose output is corrupted on win32;
```
https://github.com/envoyproxy/envoy/blob/master/bazel/foreign_cc/BUILD

envoy_cmake_external(
    name = "ares",
    cache_entries = {
        "CARES_SHARED": "no",
        "CARES_STATIC": "on",
        "CMAKE_BUILD_TYPE": "RelWithDebInfo",
        # Disable ranlib because it is not handled by bazel, and therefore
        # doesn't respect custom toolchains such as the Android NDK,
        # see https://github.com/bazelbuild/rules_foreign_cc/issues/252
        "CMAKE_RANLIB": "",
    },
    copy_pdb = True,
    lib_source = "@com_github_c_ares_c_ares//:all",
    pdb_name = "c-ares",
    static_libraries = select({
        "//bazel:windows_x86_64": ["cares.lib"],
        "//conditions:default": ["libcares.a"],
    }),
)
```

**Comment by irengrig** [comment]
@wrowe sorry I do not really understand what you mean. Is the output still corrupted after we corrected the windows toolchain file?

**Comment by wrowe** [comment]
It appears the output is no longer corrupted, thx! (Contrasted with sed to confirm possible corruption, and none was observed as the output from foreign_build_bazel copy rules.)

**Comment by irengrig** [comment]
Thank you for confirming that it works!

**Pull request merged**
