### PR TITLE
[Ninja] Symlink only top level directory contents

### LINKED ISSUE #804: Symlinking Files on Windows is Slow
I noticed that the `ninja` script calls [symlink_contents_to_dir](https://github.com/bazelbuild/rules_foreign_cc/blob/41f24f3a2f9c7b48db8bcd16d729cff6c26cd115/foreign_cc/ninja.bzl#L54). That function then will walk through the entire directory file per file and symlink one by one (see [declaration](https://github.com/bazelbuild/rules_foreign_cc/blob/4ee863c1fc88b554b9b185f192eaadd2e44c011e/foreign_cc/private/framework/toolchains/windows_commands.bzl#L98)).

I couldn't actually figure out any particular reason for symlinking each file at a time. The one special handling is for a few specific files that are copied instead, where the comments mention it is necessary to copy them to call [replace_in_files](https://github.com/bazelbuild/rules_foreign_cc/blob/4ee863c1fc88b554b9b185f192eaadd2e44c011e/foreign_cc/private/framework/toolchains/windows_commands.bzl#L142). However, `replace_in_files` is used nowhere on the ninja flow.

The issue is that symlinking on windows is _very_ expensive, and anecdotally it can >1hr for symlinking ~25k files on my GCE windows VM with a network SSD. This is likely also the problem behind #720.

My quick hacked local changes show that symlinking the entire folder still "works" (that is, my ninja build invoked through `rules_foreign_cc succeeds). Am I missing the reason why we can't symlink all of them? Should I send in a PR to change that? (At least on windows? Maybe under a flag/attribute?)

### PR DESCRIPTION
**Pull request by rubensf**
Fix #804

### CODE REVIEW

**Comment by UebelAndre** [comment]
Sorry for the massive delay here. I unfortunately don't feel confident about these changes or know how to gain confidence here. I personally think `rules_foreign_cc` is bottle-necked by the need for a process wrapper written in some testable language (https://github.com/bazelbuild/rules_foreign_cc/issues/655) before more changes can be made. Otherwise each change seems to bring a higher risk of regression. I'll defer to @jsharpe  for this but think at the very least this change needs to use the `foreign_cc` framework.

**Comment by jsharpe** [comment]
Apologies it has taken me so long to take a look at this PR; I have limited bandwidth at the moment for looking at rules_foreign_cc stuff.

This doesn't fix #720 unfortunately as this change only affects ninja and #720 uses make.

If symlink_to_dir is so slow on windows what happens if we change the implementation to copy instead or symlink on windows? I'll put together a PR to see if this works.
I kind of wanted to see symlink_to_dir modified so that it only links the directories at the highest level it can rather than recursing down and symlinking the files individually.

**Comment by jsharpe** [comment]
@rubensf any change you could take a look at #812 and see if that solves the performance issues for symlinking?

**Comment by rubensf** [comment]
@jsharpe unfortunately the copying is still quite slow - the project we're compiling also checks out some binaries and other dependencies, totally a few gigabytes of data. I updated the comment to remove the #720 fix.

@UebelAndre I'll try to change this in a way that uses the `foreign_cc` framework (but it'll certainly take a while before I get to it :)

**Pull request closed without merging**
