### PR TITLE
Add config for building with spawn_strategy=standalone

### PR DESCRIPTION
**Pull request by jsharpe**
Adds tests for building with `standalone` strategy as this seems to be picking up issues in the shell toolchain.

### CODE REVIEW

**Comment by jsharpe** [comment]
Hmm setting a `action_env` doesn't quite seem enough to defeat the caching of the sandboxed build strategy. The macOS build should fail in building `@rules_foreign_cc//toolchains:make_tool` because it does for me locally with a clean WORKSPACE. @UebelAndre any ideas?

**Comment by UebelAndre** [comment]
> Hmm setting a `action_env` doesn't quite seem enough to defeat the caching of the sandboxed build strategy. The macOS build should fail in building `@rules_foreign_cc//toolchains:make_tool` because it does for me locally with a clean WORKSPACE. @UebelAndre any ideas?

Just to close the loop on this you ended up going with `--compilation_mode=dbg`?

**Comment by jsharpe** [comment]
> > Hmm setting a `action_env` doesn't quite seem enough to defeat the caching of the sandboxed build strategy. The macOS build should fail in building `@rules_foreign_cc//toolchains:make_tool` because it does for me locally with a clean WORKSPACE. @UebelAndre any ideas?
> 
> Just to close the loop on this you ended up going with `--compilation_mode=dbg`?

Yes

**Comment by jsharpe** [comment]
PTAL @UebelAndre

**Review by UebelAndre — APPROVED** [review]
Awesome work!

**Pull request merged**
