### PR TITLE
Removed `make_commands` attribute and fixed `configure_make`

### PR DESCRIPTION
**Pull request by UebelAndre**
Attributes which encourage users to write raw bash are generally non-hermetic and lead to a bunch of difficult edge cases to account for. The `targets` attribute is far more desirable since it allows the rules to provide stable and consistent APIs across all the rules. 

Additionally, this change fixes an inconsistency with `configure_make` where the targets API was not being used.
closes https://github.com/bazelbuild/rules_foreign_cc/issues/670

### CODE REVIEW

**Comment by UebelAndre** [comment]
I think as part of this change I should also add an example of how to have a custom make binary to replace, what seems like, a common pattern where users use `make_commands` to prefix or change the tool being used based on the host's configuration. This is definitely not recommended but we should find a recommended approach. 

[This comment](https://github.com/bazelbuild/rules_foreign_cc/issues/668#issuecomment-858037712) describes such an approach but I'm not sure if it encompasses enough of the functionality.

**Comment by UebelAndre** [comment]
> I think as part of this change I should also add an example of how to have a custom make binary to replace, what seems like, a common pattern where users use `make_commands` to prefix or change the tool being used based on the host's configuration. This is definitely not recommended but we should find a recommended approach.
> 
> [This comment](https://github.com/bazelbuild/rules_foreign_cc/issues/668#issuecomment-858037712) describes such an approach but I'm not sure if it encompasses enough of the functionality.

I think https://github.com/bazelbuild/rules_foreign_cc/pull/676 would solve for this in a way that makes transitioning easier since it doesn't require users to setup a toolchain

**Comment by UebelAndre** [comment]
This PR is blocked until https://github.com/bazelbuild/rules_foreign_cc/pull/676 is resolved

**Comment by attilaolah** [comment]
Cool, this is unblocked now!

By the way, once this gets merged, and now that #676 is merged too, it would be really handy to have a new release :)

**Comment by UebelAndre** [comment]
@attilaolah This one is ready for review. Let me know if it solves the last issue you're having.

**Comment by attilaolah** [comment]
I'll probably have some timet o take a look at this later today. Running some build tests now to make sure that I have a clean/passing build before patching in this one.

**Comment by attilaolah** [comment]
OK I patched in this change, and all my builds still pass, and the `targets` and `angs` are both working as expected with `configure_make()`. I think this is good to go!

**Review by attilaolah — APPROVED** [review]

**Pull request merged**
