### PR TITLE
Fix pkgconfig for configure_make and make

### PR DESCRIPTION
**Pull request by whs-dot-hk**
Currently, `configure_make` and `make` resolve build dependencies through flags e.g. `LDFLAGS`, only. Both `PKG_CONFIG_PATH` and pkgconfig files are broken. Which causes builds fail most of the time.

#344

### CODE REVIEW

**Comment by panzhongxian** [comment]
This PR commit can't build the openssl while the master can. The BUILD file are as following:
```python
configure_make(
    name = "openssl",
    configure_command = "config",
    configure_options = [
        "no-shared",
    ],
    lib_source = "@openssl//:all",
    static_libraries = [
        "libssl.a",
        "libcrypto.a",
    ],
    visibility = ["//visibility:public"],
)
```
I find that the master uses `"$EXT_BUILD_ROOT/external/openssl/config"`  instead of `config`.

**Comment by whs-dot-hk** [comment]
Hi, @panzhongxian Are you using my master? I have customize my master. Try my `fix-pkgconfig` branch.

It should build both openssl shared and static libraries with no problem.
```starlark
load("@rules_foreign_cc//tools/build_defs:configure.bzl", "configure_make")

filegroup(
    name = "all",
    srcs = glob(["**"]),
)

configure_make(
    name = "library",
    lib_source = ":all",
    configure_command = "config",
    shared_libraries = [
        "libssl.so",
        "libcrypto.so",
    ],
    visibility = ["//visibility:public"],
)

configure_make(
    name = "static_library",
    lib_source = ":all",
    configure_command = "config",
    configure_options = [
        "no-shared",
    ],
    static_libraries = [
        "libssl.a",
        "libcrypto.a",
    ],
    visibility = ["//visibility:public"],
)
```

**Comment by panzhongxian** [comment]
👍  the `fix-pkgconfig` branch works well.

sorry for my carelessness.

**Review by jsharpe — APPROVED** [review]
Thanks @whs-dot-hk !

**Pull request merged**
