### PR TITLE
Add regression tests for python dependencies

### PR DESCRIPTION
**Pull request by jheaff1**
This pull request adds regression tests for building dependencies of Python2 and Python3. This PR is a precursor to a PR which will provide the ability to build a hermetic Python2/3 toolchain using rules_foreign_cc

### CODE REVIEW

**Comment by UebelAndre** [comment]
Can this PR be repurposed into just adding all the python dependencies if https://github.com/bazelbuild/rules_foreign_cc/pull/650 makes it in (and is indeed the key to getting them working)? It'd be nice to reduce the footprint of https://github.com/bazelbuild/rules_foreign_cc/pull/622

**Comment by jheaff1** [comment]
> Can this PR be repurposed into just adding all the python dependencies if #650 makes it in (and is indeed the key to getting them working)? It'd be nice to reduce the footprint of #622

Sure I can do that. Perhaps instead I should open a separate PR for that and then this PR can continue to be focused on building a hermetic Python toolchain?

**Comment by UebelAndre** [comment]
I thought https://github.com/bazelbuild/rules_foreign_cc/pull/622 was providing that but yeah, having the examples separate could also work. I might even absorb the dependencies in https://github.com/bazelbuild/rules_foreign_cc/pull/650 which I think is appropriate since it would be providing the change and a regression test. That's probably best?

**Comment by jheaff1** [comment]
> I thought #622 was providing that but yeah, having the examples separate could also work. I might even absorb the dependencies in #650 which I think is appropriate since it would be providing the change and a regression test. That's probably best?

Sorry I got this PR mixed up with #622. Im happy to repurpose this PR to add the python dependencies to the examples (apr, apr_util, SQLite, subversion)

**Comment by jheaff1** [comment]
@UebelAndre I have now repurposed this PR to provide regression tests for Python dependencies :)

**Review by UebelAndre — APPROVED** [review]
Oops, I should have merged this in the earlier PR. Thanks so much for catching this!!

**Comment by jheaff1** [comment]
@UebelAndre Sadly the build for subversion fails. I reverted commit 9932c7dbc2ef0dd15d60685172e71c350f757069 and it passes for me locally

**Comment by UebelAndre** [comment]
For expedience sake, I opened https://github.com/bazelbuild/rules_foreign_cc/pull/682

**Comment by UebelAndre** [comment]
> @UebelAndre Sadly the build for subversion fails. I reverted commit [9932c7d](https://github.com/bazelbuild/rules_foreign_cc/commit/9932c7dbc2ef0dd15d60685172e71c350f757069) and it passes for me locally (on linux)

Ah, that actually makes sense. That change fixed the fact that the `targets` attribute was being ignored. So the build commands that were actually in use were actually being used were simply
```bash
make 
make install
```
instead of the configured `bin` and `install` targets. This means when we ran `install` only having produced `bin`, we ran into an error for missing files.

**Comment by UebelAndre** [comment]
With https://github.com/bazelbuild/rules_foreign_cc/pull/677#issuecomment-862436317 said and https://github.com/bazelbuild/rules_foreign_cc/pull/682 merged, I'll close this PR but again, thanks @jheaff1 for putting this together. I would have made changes here if github made it easier to suggest arbitrary changes.

**Comment by jheaff1** [comment]
> With [#677 (comment)](https://github.com/bazelbuild/rules_foreign_cc/pull/677#issuecomment-862436317) said and #682 merged, I'll close this PR but again, thanks @jheaff1 for putting this together. I would have made changes here if github made it easier to suggest arbitrary changes.

No problem at all, thanks for your help!

**Pull request closed without merging**
