### PR TITLE
Add setup_args and run `meson setup` explictly

### LINKED ISSUE #1170: Add a `setup_args` argument to the meson rule
As discussed in #986,  a `setup_args` argument to the meson rule similar to `build_args` and `install_args` for the other steps should be added.

_Originally posted by @sfc-gh-mfickert in https://github.com/bazelbuild/rules_foreign_cc/issues/986#issuecomment-1432936301_

CC @jheaff1

### PR DESCRIPTION
**Pull request by allsey87**
Resolves #1170

### CODE REVIEW

**Comment by allsey87** [comment]
The failed test seems to be an issue with the MacOS runners. I have seen this on a couple projects/CI systems lately.

**Comment by jsharpe** [comment]
The buildifier failure is an issue in this PR:
image

The macOS failures do seem to correlate with the switch to use VMs in bazel's CI; I suspect they've either bumped macOS version or are missing some preinstalled tooling that we depend on as main is also failing.

**Comment by jsharpe** [comment]
@jheaff1 do you have time to review the changes in this PR?

**Comment by allsey87** [comment]
> The buildifier failure is an issue in this PR

Fixed in c7bcf7d

**Comment by jsharpe** [comment]
Looks like the other macOS failures are due to the runners upgrading the version of XCode installed.. The fix for this likely needs to come in the apple toolchain.

**Comment by allsey87** [comment]
I think this is ready for review?

**Review by jsharpe — APPROVED** [review]
Without really knowing meson, this seems a reasonable change and CI is now all green so I'm happy with this.

**Pull request merged**
