### PR TITLE
Cater for different drive letters when normalizing path

### PR DESCRIPTION
**Pull request by matt-sm**
` _normalize_path()` fails to normalize paths containing different drive letters eg.

`C:\foo;F:\bar` is converted to `/c/foo:F:\bar`

This change will ensure paths containing different drive letters are also normalized eg.

`C:\foo;F:\bar` is converted to `/C/foo:/F/bar`

### CODE REVIEW

**Comment by matt-sm** [comment]
@jsharpe is this something you would consider merging?

**Comment by jsharpe** [comment]
> @jsharpe is this something you would consider merging?

Yes; but its annoying that windows CI is getting SSL certificate errors on Windows so that we can't easily verify this PR; its been a while since I've had to develop on windows, and I've never used bazel on Windows so we definitely rely on contributions from the community that do use windows to enhance the capability on that platform!

**Comment by matt-sm** [comment]
What is the fix for the CI certificate errors?

**Comment by jsharpe** [comment]
> What is the fix for the CI certificate errors?

I don't know I'm afraid - not sure if this is infra related, bazel 7, or a problem in our rules..

**Comment by mishazharov** [comment]
I took a quick look and was able to fix the CI issue: https://github.com/bazelbuild/rules_foreign_cc/pull/1171

**Review by jsharpe — APPROVED** [review]
LGTM thanks!

**Pull request merged**
